### ISSUE TITLE
Support for installing splunk apps from local file

### ISSUE THREAD

**Issue by mkristan** [chef-cookbooks/chef-splunk#111]
### Cookbook version
1.7.3

### Chef-client version
14.5.33

### Platform Details
CentOS 7.5 (VirtualBox via Vagrant)

### Scenario:
Feature Request: Ability to install Splunk Apps via local file instead of remote file

### Steps to Reproduce:
Assume that we download the app package (.tar.gz) onto the local system through a method aside from remote_file (ex. download from an S3 bucket or copied onto a system through an out of band method), I'd like to point to a local path (ex. /tmp/splunk_special_app.tar.gz) and install directly.  

### Expected Result:
Using the remote_file method fails, even if I specify file://tmp/splunk_special_app.tar.gz.  I would expect the splunk_app resource to look something like this:

splunk_app 'sanitycheck' do
  local_file '/tmp/sanitycheck.tar.gz'
  splunk_auth 'admin:notarealpassword'
  action :install
end

**Comment by nvwls** [comment]
You can use `remote_file 'file:///tmp/sanitycheck.tar.gz'`

**Comment by haidangwa** [comment]
I think this can be done rather easily; however, with so many ways to "unpack" a compressed bundle file (e.g., tar.gz, zip, bz2), this feature should not attempt to support any/all of the possibilities. In contrast, this feature should support installing an app from any local source on the chef node and into the /opt/splunk/etc/apps directory, unless otherwise specified by the `app_dir` property.
