### ISSUE TITLE
disable Transparent Hugepages in recipe

### ISSUE THREAD

**Issue by bby-bishopclark** [chef-cookbooks/chef-splunk#114]
As a feature request, please consider adding a snippet to disable THP on linux hosts, so that the recipe mirrors what consultants seem to be recommending for better performance.

Based on the alternatives, I'd recommend a simple change to Grub (/etc/default/grub if it's there; /etc/grub.conf if not (EL<7)).

```
sed -i~ '
  /GRUB_CMDLINE_LINUX/s/"$/transparent_hugepage=never"/
' /etc/default/grub

sed -i~ '
  /^[^#]kernel /s/$/ transparent_hugepage=never/
' /etc/grub.conf
```

... but I don't relish that task due to the risk!  (no, there's no simple sysctl tweak that I saw)

**Comment by haidangwa** [comment]
This seems more of an optimization for linux kernel tuning rather than a Splunk configuration issue. There are a number of community-sourced cookbooks that deal with this, which IMHO is out of scope for this cookbook. I would recommend searching in [Chef Supermarket](https://supermarket.chef.io). Perhaps this will work for you: https://supermarket.chef.io/cookbooks/disable-thp

**Comment by bby-bishopclark** [comment]
If only there was some sort of dependency mechanism to ensure the product that needs the crutch, gets the crutch.

Oh!  Happy "almost a year without a vendor response" Birthday for this ticket!
