### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by burnzy** [chef-cookbooks/chef-splunk#20]
Could we add windows support for this cookbook?

**Comment by spuder** [comment]
+1

**Comment by spuder** [comment]
I'm looking at how this could be implemented. First obstacle is finding the download link that doesn't require authentication. 


### Linux
http://download.splunk.com/releases/6.2.1/universalforwarder/linux/splunkforwarder-6.2.1-245427-linux-2.6-x86_64.rpm

I've not been able to guess the URL for windows. The url the browser shows is 

http://www.splunk.com/page/download_track?file=6.2.1/universalforwarder/windows/splunkforwarder-6.2.1-245427-x64-release.msi&platform=Windows&architecture=x86_64&version=6.2.1&product=splunk&typed=release&name=windows_installer

I'm assuming that it should look like this:

http://download.splunk.com/releases/6.3.3/universalforwarder/windows/splunk-6.3.3-f44afce176d0-x64-release.msi

**Comment by derekgroh** [comment]
http://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=windows&version=6.3.3&product=universalforwarder&filename=splunkforwarder-6.3.3-f44afce176d0-x64-release.msi&wget=true

**Comment by rarsan** [comment]
Splunk recently changed the download URIs. Here's the one you're looking for:
http://download.splunk.com/products/splunk/releases/6.3.3/windows/splunk-6.3.3-f44afce176d0-x64-release.msi

**Comment by spuder** [comment]
Instead of downloading the release directly, it would probably be better to use chocolatey packages. 

https://chocolatey.org/packages/splunkforwarder

**Comment by haidangwa** [comment]
I think that since the node attributes allow for specifying any download URL an implementer needs, this cookbook shouldn't have to be modified to accommodate any particular URL preference. As new versions are released, the default version and URL in this cookbook will constantly need to be updated, which can be easily done in a role or environment attribute setting or in a wrapper cookbook of choice.

The primary enhancement I think that is in scope for this cookbook is detecting when a splunk forwarder bundle is an MSI and using the appropriate package resource to install it. I don't know if there is a need to support installing splunk server on Windows, as I do not have experience with the server running on Windows either -- don't know many implementations where Splunk Server is installed on a Windows server, as well.
