### ISSUE TITLE
client.rb recipe forces auth recipe, but why?

### ISSUE THREAD

**Issue by Sauraus** [chef-cookbooks/chef-splunk#37]
The client.rb does not needed to run successfully on a Splunk system that does not require any auth to push logs, this is an unnecessary burden on such systems.

**Comment by jblaine** [comment]
Perhaps you misunderstand what password is being configured.

The `client` recipe includes `setup_auth` because changing the **local client** Splunk admin password from `changeme` is an obvious good practice. That `changeme` password applies to various commands being run in `/opt/splunkforwarder/bin` which talk to the local client's Splunk forwarder instance.

It has nothing to do with forwarder <-> Splunk Server interactions.

**Comment by iennae** [comment]
@Sauraus This looks like it got resolved based on 
include_recipe 'chef-splunk::setup_auth' if node['splunk']['setup_auth']

If this is still an issue for you, please reopen with additional details. Thanks.
